export const FETCH_FILE_REQUEST = 'FETCH_FILE_REQUEST'
export const FETCH_FILE_SUCCESS = 'FETCH_FILE_SUCCESS'
export const FETCH_FILE_FAILURE = 'FETCH_FILE_FAILURE'

export const FETCH_SINGLE_FILE_REQUEST = 'FETCH_SINGLE_FILE_REQUEST'
export const FETCH_SINGLE_FILE_SUCCESS = 'FETCH_SINGLE_FILE_SUCCESS'
export const FETCH_SINGLE_FILE_FAILURE = 'FETCH_SINGLE_FILE_FAILURE'
